#!/bin/bash
# ts_mkweb
# sassenbergm
echo $HDR > $HOME/public_html/timesheet.html
cat $HOME/public_html/timesheet.log >> $HOME/public_html/timesheet.html
echo $FTR >> $HOME/public_html/timesheet.html
#eof

